# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a6ff71caebc996c8f4d5403020add5a5beb9f0ad754543c5aac281d7516cb48d6e729852edee5fb29dc00b882c9a1620ca09988c39fb5b373d6b89da87fb692

test:
  secret_key_base: d4e83d9f628f923cfc544565a5bdd819900b253c4bbd4065832f52e1523d095293aaa2de96b45f045237a0e1b3a0645c662cbb626ae8292a63d117a7222279d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
